name: npm-publish-latest
on:
  push:
    branches:
      - release
jobs:
  npm-publish:
    name: npm-publish-latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        tag: "latest"
