name: npm-publish-dev
on:
  push:
    branches:
      - master
jobs:
  npm-publish:
    name: npm-publish-dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_AUTH_TOKEN }}
        tag: "dev"
